### ISSUE TITLE
[Pop Up]- No pop up with a message is displayed when the game result is draw

### ISSUE THREAD

**Issue by SharvariAbhishek** [softwaretestingmasterclass/androidAppTesting#3]
Bug Priority: Critical
Description: When the game result is draw, a pop up should be displayed saying that the -Draw! Try it again
Precondition: The game must be installed on user's device
Steps to reproduce: Click on the play button in IDE and start playing the game. 
Expected result: A pop up with a message should be displayed- Draw! Try it again
Actual result:  No Pop up with a message is displayed
=========================================================================
![error screenshot](https://user-images.githubusercontent.com/28744194/102022244-62357480-3d3a-11eb-91ae-26548a326023.jpg)

**Comment by SharvariAbhishek** [comment]
Error logs:
============================================================================
2020-12-13 12:13:06.028 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at java.util.ArrayList.get(ArrayList.java:437)
2020-12-13 12:13:06.028 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at morteza.packag.com.tictactoekotlin.TicTacToeActivity.action(TicTacToeActivity.kt:149)
2020-12-13 12:13:06.028 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at morteza.packag.com.tictactoekotlin.TicTacToeActivity.imageButtonTapped(TicTacToeActivity.kt:99)
2020-12-13 12:13:06.028 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-13 12:13:06.028 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
2020-12-13 12:13:06.028 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.view.View.performClick(View.java:7448)
2020-12-13 12:13:06.028 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.view.View.performClickInternal(View.java:7425)
2020-12-13 12:13:06.028 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.view.View.access$3600(View.java:810)
2020-12-13 12:13:06.029 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.view.View$PerformClick.run(View.java:28305)
2020-12-13 12:13:06.029 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2020-12-13 12:13:06.029 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-12-13 12:13:06.029 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.os.Looper.loop(Looper.java:223)
2020-12-13 12:13:06.029 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
2020-12-13 12:13:06.029 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-13 12:13:06.029 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2020-12-13 12:13:06.029 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2020-12-13 12:13:08.109 17146-17208/morteza.packag.com.tictactoekotlin D/OpenGLRenderer: endAllActiveAnimators on 0xe1f60a10 (RippleDrawable) with handle 0xe866f8d0
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at java.util.ArrayList.get(ArrayList.java:437)
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at morteza.packag.com.tictactoekotlin.TicTacToeActivity.action(TicTacToeActivity.kt:149)
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at morteza.packag.com.tictactoekotlin.TicTacToeActivity.imageButtonTapped(TicTacToeActivity.kt:99)
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.view.View.performClick(View.java:7448)
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.view.View.performClickInternal(View.java:7425)
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.view.View.access$3600(View.java:810)
2020-12-13 12:13:34.977 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.view.View$PerformClick.run(View.java:28305)
2020-12-13 12:13:34.978 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2020-12-13 12:13:34.978 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-12-13 12:13:34.978 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.os.Looper.loop(Looper.java:223)
2020-12-13 12:13:34.978 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
2020-12-13 12:13:34.978 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-13 12:13:34.978 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2020-12-13 12:13:34.978 17146-17146/morteza.packag.com.tictactoekotlin W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
